teleop_twist_joy:
  ros__parameters:
    axis_linear:  # Left thumb stick vertical
      x: 1
      y: 0
    scale_linear:
      x: 1.5
      y: 1.5
    scale_linear_turbo:
      x: 2.5
      y: 2.5

    axis_angular:  # Left thumb stick horizontal
      yaw: 2
    scale_angular:
      yaw: 1.5
    scale_angular_turbo:
      yaw: 2.5

    enable_button: 5  # Left trigger button
    enable_turbo_button: 7  # Right trigger button